openapi: 3.0.3
info:
  title: Security Example API
  description: This API demonstrates the effect of using Security at the API, Service
    or Method levels
  version: "1.0"
servers:
- url: http://localhost:80
  description: Default server for hierarchy
paths:
  /default:
    get:
      tags:
      - default_service
      summary: default default_service
      description: The default service default_method is secured with basic authentication
      operationId: default_service#default
      responses:
        "204":
          description: No Content response.
      security:
      - basic_header_Authorization: []
  /svc/default:
    get:
      tags:
      - api_key_service
      summary: default api_key_service
      operationId: api_key_service#default
      responses:
        "204":
          description: No Content response.
      security:
      - api_key_header_Authorization: []
  /svc/secure:
    get:
      tags:
      - api_key_service
      summary: secure api_key_service
      description: This method requires a valid JWT token.
      operationId: api_key_service#secure
      responses:
        "204":
          description: No Content response.
      security:
      - jwt_header_Authorization: []
components:
  securitySchemes:
    api_key_header_Authorization:
      type: apiKey
      description: Secures endpoint by requiring an API key.
      name: Authorization
      in: header
    basic_header_Authorization:
      type: http
      description: Basic authentication
      scheme: basic
    jwt_header_Authorization:
      type: http
      description: Secures endpoint by requiring a valid JWT token.
      scheme: bearer
tags:
- name: api_key_service
  description: The svc service is secured with API key based authentication
- name: default_service
security:
- basic__: []
