swagger: "2.0"
info:
  title: Security Example API
  description: This API demonstrates the effect of using Security at the API, Service
    or Method levels
  version: ""
host: localhost:80
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /default:
    get:
      tags:
      - default_service
      summary: default default_service
      description: The default service default_method is secured with basic authentication
      operationId: default_service#default
      parameters:
      - name: Authorization
        in: header
        description: Basic Auth security using Basic scheme (https://tools.ietf.org/html/rfc7617)
        required: false
        type: string
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
      security:
      - basic_header_Authorization: []
  /svc/default:
    get:
      tags:
      - api_key_service
      summary: default api_key_service
      operationId: api_key_service#default
      parameters:
      - name: Authorization
        in: header
        description: API key used for authentication
        required: true
        type: string
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
      security:
      - api_key_header_Authorization: []
  /svc/secure:
    get:
      tags:
      - api_key_service
      summary: secure api_key_service
      description: This method requires a valid JWT token.
      operationId: api_key_service#secure
      parameters:
      - name: Authorization
        in: header
        description: JWT used for authentication
        required: true
        type: string
      responses:
        "204":
          description: No Content response.
      schemes:
      - http
      security:
      - jwt_header_Authorization: []
securityDefinitions:
  api_key_header_Authorization:
    type: apiKey
    description: Secures endpoint by requiring an API key.
    name: Authorization
    in: header
  basic_header_Authorization:
    type: basic
    description: Basic authentication
  jwt_header_Authorization:
    type: apiKey
    description: Secures endpoint by requiring a valid JWT token.
    name: Authorization
    in: header
