openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for calc
paths:
    /:
        post:
            tags:
                - calc
            summary: divide calc
            operationId: calc#divide
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DivideRequestBody'
                        example:
                            dividend: 3793862871819669726
                            divisor: 8399553735696626949
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DivideResponseBody'
                            example:
                                quotient: 360622074634248926
                                reminder: 8133055152903002499
                "400":
                    description: 'div_by_zero: Response used for division by zero errors'
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DivByZero'
                            example:
                                message: Minima error ullam eius odio minima ipsam.
                "504":
                    description: 'timeout: Operation timed out'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
components:
    schemas:
        DivByZero:
            type: object
            properties:
                message:
                    type: string
                    description: division by zero leads to infinity.
                    example: Molestiae modi quo est.
            description: DivByZero is the error returned when using value 0 as divisor.
            example:
                message: Eum aut adipisci temporibus laboriosam et.
            required:
                - message
        DivideRequestBody:
            type: object
            properties:
                dividend:
                    type: integer
                    example: 6339444414280965279
                    format: int64
                divisor:
                    type: integer
                    example: 2998957498373416763
                    format: int64
            example:
                dividend: 669093391323277721
                divisor: 6850943989821012471
            required:
                - dividend
                - divisor
        DivideResponseBody:
            type: object
            properties:
                quotient:
                    type: integer
                    example: 2082938806418090480
                    format: int64
                reminder:
                    type: integer
                    example: 817058348830766028
                    format: int64
            example:
                quotient: 3322573843781975777
                reminder: 499723715072376515
            required:
                - quotient
                - reminder
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
tags:
    - name: calc
