// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "appengine": Application Media Types
//
// Command:
// $ goagen
// --design=github.com/goadesign/examples/appengine/design
// --out=$(GOPATH)/src/github.com/goadesign/examples/appengine
// --version=v1.3.1

package app

// example MediaType (default view)
//
// Identifier: application/vnd.example+json; view=default
type Example struct {
	Message *string `form:"message,omitempty" json:"message,omitempty" yaml:"message,omitempty" xml:"message,omitempty"`
}
