openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for hello
paths:
    /hello/{greeting}:
        get:
            tags:
                - hello
            summary: hello hello
            operationId: hello#hello
            parameters:
                - name: greeting
                  in: path
                  description: The greeting message
                  required: true
                  schema:
                    type: string
                    description: The greeting message
                    example: Porro quas nobis ea.
                  example: Quae est possimus eius architecto.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Hello'
                            example:
                                greeting: Ullam sequi quidem qui in et excepturi.
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Hello'
                            example:
                                greeting: Aut iste labore provident incidunt aut enim.
                "202":
                    description: Accepted response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/Hello'
                            example:
                                greeting: Iste ratione voluptatum.
components:
    schemas:
        Hello:
            type: object
            properties:
                greeting:
                    type: string
                    description: The greeting message
                    example: Perspiciatis laboriosam voluptatem sunt maxime quae.
            example:
                greeting: Et molestiae.
            required:
                - greeting
tags:
    - name: hello
      description: The hello service returns greetings with various statuses.
