// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "appengine": hello Resource Client
//
// Command:
// $ goagen
// --design=github.com/goadesign/examples/appengine/design
// --out=$(GOPATH)/src/github.com/goadesign/examples/appengine
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ShowHelloPath computes a request path to the show action of hello.
func ShowHelloPath() string {

	return fmt.Sprintf("/hello/")
}

// ShowHello makes a request to the show action endpoint of the hello resource
func (c *Client) ShowHello(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewShowHelloRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewShowHelloRequest create the request corresponding to the show action endpoint of the hello resource.
func (c *Client) NewShowHelloRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
