// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "appengine": Application User Types
//
// Command:
// $ goagen
// --design=github.com/goadesign/examples/appengine/design
// --out=$(GOPATH)/src/github.com/goadesign/examples/appengine
// --version=v1.3.1

package client
