openapi: 3.0.3
info:
    title: Encodings Service
    description: Encoding example service demonstrating the use of different content types
    version: 0.0.1
servers:
    - url: http://localhost:80
paths:
    /concatbytes/{a}/{b}:
        get:
            tags:
                - text
            summary: concatbytes text
            operationId: text#concatbytes
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Dolorum molestias sed dolorem unde numquam laudantium.
                  example: Dolorum molestias sed dolorem unde numquam laudantium.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Ut repudiandae velit qui rerum aut eaque.
                  example: Ut repudiandae velit qui rerum aut eaque.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example:
                                    - 73
                                    - 109
                                    - 112
                                    - 101
                                    - 100
                                    - 105
                                    - 116
                                    - 32
                                    - 113
                                    - 117
                                    - 105
                                    - 46
                                format: binary
                            example:
                                - 73
                                - 109
                                - 112
                                - 101
                                - 100
                                - 105
                                - 116
                                - 32
                                - 113
                                - 117
                                - 105
                                - 46
    /concatbytesfield/{a}/{b}:
        get:
            tags:
                - text
            summary: concatbytesfield text
            operationId: text#concatbytesfield
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Quasi itaque.
                  example: Quasi itaque.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Culpa ratione.
                  example: Culpa ratione.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example:
                                    - 69
                                    - 116
                                    - 32
                                    - 101
                                    - 110
                                    - 105
                                    - 109
                                    - 32
                                    - 113
                                    - 117
                                    - 105
                                    - 97
                                    - 46
                                format: binary
                            example:
                                - 69
                                - 116
                                - 32
                                - 101
                                - 110
                                - 105
                                - 109
                                - 32
                                - 113
                                - 117
                                - 105
                                - 97
                                - 46
    /concatstringfield/{a}/{b}:
        get:
            tags:
                - text
            summary: concatstringfield text
            operationId: text#concatstringfield
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Ipsa qui expedita consectetur et et labore.
                  example: Ipsa qui expedita consectetur et et labore.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Fuga dolorum quaerat.
                  example: Fuga dolorum quaerat.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example: Qui exercitationem cupiditate ut ratione non consequatur.
                            example: Qui exercitationem cupiditate ut ratione non consequatur.
    /concatstrings/{a}/{b}:
        get:
            tags:
                - text
            summary: concatstrings text
            operationId: text#concatstrings
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Nam ut eligendi quia laudantium non quia.
                  example: Nam ut eligendi quia laudantium non quia.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Officia aliquid aut quis minus.
                  example: Officia aliquid aut quis minus.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example: Non repudiandae ex velit pariatur.
                            example: Non repudiandae ex velit pariatur.
    /swagger.json:
        get:
            tags:
                - text
            summary: Download ../../gen/http/openapi.json
            operationId: text#/swagger.json
            responses:
                "200":
                    description: File downloaded
components: {}
tags:
    - name: text
      description: The text service performs operations on strings
