openapi: 3.0.3
info:
    title: Encodings Service
    description: Encoding example service demonstrating the use of different content types
    version: 0.0.1
servers:
    - url: http://localhost:80
paths:
    /concatbytes/{a}/{b}:
        get:
            tags:
                - text
            summary: concatbytes text
            operationId: text#concatbytes
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Cupiditate perferendis excepturi corrupti sint aspernatur.
                  example: Nobis inventore nesciunt ex repellendus excepturi qui.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Dolorem perspiciatis officiis ipsum delectus.
                  example: Molestiae ducimus pariatur tenetur.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example:
                                    - 79
                                    - 100
                                    - 105
                                    - 111
                                    - 32
                                    - 115
                                    - 101
                                    - 100
                                    - 32
                                    - 111
                                    - 109
                                    - 110
                                    - 105
                                    - 115
                                    - 46
                                format: binary
                            example:
                                - 79
                                - 100
                                - 105
                                - 111
                                - 32
                                - 115
                                - 101
                                - 100
                                - 32
                                - 111
                                - 109
                                - 110
                                - 105
                                - 115
                                - 46
    /concatbytesfield/{a}/{b}:
        get:
            tags:
                - text
            summary: concatbytesfield text
            operationId: text#concatbytesfield
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Vitae assumenda fugiat et sit repellendus.
                  example: Suscipit at et iste laudantium ullam necessitatibus.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Ut tempore.
                  example: Ut ut ex rem.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example:
                                    - 86
                                    - 101
                                    - 110
                                    - 105
                                    - 97
                                    - 109
                                    - 32
                                    - 118
                                    - 111
                                    - 108
                                    - 117
                                    - 112
                                    - 116
                                    - 97
                                    - 116
                                    - 101
                                    - 109
                                    - 46
                                format: binary
                            example:
                                - 86
                                - 101
                                - 110
                                - 105
                                - 97
                                - 109
                                - 32
                                - 118
                                - 111
                                - 108
                                - 117
                                - 112
                                - 116
                                - 97
                                - 116
                                - 101
                                - 109
                                - 46
    /concatstringfield/{a}/{b}:
        get:
            tags:
                - text
            summary: concatstringfield text
            operationId: text#concatstringfield
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Qui delectus reprehenderit laudantium tempora autem.
                  example: Quisquam hic adipisci qui ut nisi.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Sit officia repellat.
                  example: Recusandae aut.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example: Eos veritatis est repudiandae distinctio at animi.
                            example: Eos veritatis est repudiandae distinctio at animi.
    /concatstrings/{a}/{b}:
        get:
            tags:
                - text
            summary: concatstrings text
            operationId: text#concatstrings
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Numquam unde accusantium autem tenetur.
                  example: Laborum amet odio in.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Odio inventore dolorem sunt in dolorem aut.
                  example: Magnam autem nostrum.
            responses:
                "200":
                    description: OK response.
                    content:
                        text/html:
                            schema:
                                type: string
                                example: At at.
                            example: At at.
    /swagger.json:
        get:
            tags:
                - text
            summary: Download ../../gen/http/openapi.json
            operationId: text#/swagger.json
            responses:
                "200":
                    description: File downloaded
components: {}
tags:
    - name: text
      description: The text service performs operations on strings
