openapi: 3.0.3
info:
    title: Calculator Service
    description: HTTP service for multiplying numbers, a goa teaser
    version: 0.0.1
servers:
    - url: http://localhost:8000/calc
      description: calc hosts the Calculator Service.
    - url: https://{version}.goa.design/calc
      description: calc hosts the Calculator Service.
      variables:
        version:
            default: v1
paths:
    /multiply/{a}/{b}:
        get:
            tags:
                - calc
            summary: multiply calc
            operationId: calc#multiply
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: integer
                    description: Left operand
                    example: 2827624921536156404
                    format: int64
                  example: 1382634857916332518
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: integer
                    description: Right operand
                    example: 5648438437472980127
                    format: int64
                  example: 6509684248140511211
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: integer
                                example: 4628236506152770078
                                format: int64
                            example: 4628236506152770078
    /openapi.json:
        get:
            tags:
                - calc
            summary: Download gen/http/openapi3.json
            operationId: calc#/openapi.json
            responses:
                "200":
                    description: File downloaded
components: {}
tags:
    - name: calc
      description: The calc service performs operations on numbers
