openapi: 3.0.3
info:
    title: Session service
    description: HTTP service that showcase the use of HTTP cookies in Goa services.
    version: "1.0"
servers:
    - url: http://localhost:80
      description: Default server for session
paths:
    /:
        get:
            tags:
                - session
            summary: use_session session
            operationId: session#use_session
            parameters:
                - name: SID
                  in: cookie
                  description: Session ID
                  allowEmptyValue: true
                  required: true
                  schema:
                    type: string
                    description: Session ID
                    example: Mollitia aut quis.
                  example: At mollitia itaque facere voluptas.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateSessionResponseBody'
                            example:
                                message: Omnis eligendi.
        post:
            tags:
                - session
            summary: create_session session
            operationId: session#create_session
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateSessionRequestBody'
                        example:
                            name: Ut quas sit at illum tempore ad.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateSessionResponseBody'
                            example:
                                message: Aliquam aut iste incidunt impedit maiores.
components:
    schemas:
        CreateSessionRequestBody:
            type: object
            properties:
                name:
                    type: string
                    description: Name of session
                    example: Necessitatibus eum atque ut.
            example:
                name: Quis sunt sed culpa tempore natus est.
            required:
                - name
        CreateSessionResponseBody:
            type: object
            properties:
                message:
                    type: string
                    description: User message
                    example: Et dolor.
            example:
                message: Aliquid illum dolore quasi voluptates mollitia deserunt.
            required:
                - message
tags:
    - name: session
      description: The session service illustrates managing user sessions with cookies.
