swagger: "2.0"
info:
    title: Session service
    description: HTTP service that showcase the use of HTTP cookies in Goa services.
    version: ""
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /:
        get:
            tags:
                - session
            summary: use_session session
            operationId: session#use_session
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/SessionUseSessionResponseBody'
                        required:
                            - message
            schemes:
                - http
        post:
            tags:
                - session
            summary: create_session session
            operationId: session#create_session
            parameters:
                - name: create_session_request_body
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/SessionCreateSessionRequestBody'
                    required:
                        - name
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/SessionCreateSessionResponseBody'
                        required:
                            - message
            schemes:
                - http
definitions:
    SessionCreateSessionRequestBody:
        title: SessionCreateSessionRequestBody
        type: object
        properties:
            name:
                type: string
                description: Name of session
                example: Beatae veritatis similique.
        example:
            name: Eos alias omnis labore at blanditiis quia.
        required:
            - name
    SessionCreateSessionResponseBody:
        title: SessionCreateSessionResponseBody
        type: object
        properties:
            message:
                type: string
                description: User message
                example: Molestiae sit nihil.
        example:
            message: Ut amet aspernatur.
        required:
            - message
    SessionUseSessionResponseBody:
        title: SessionUseSessionResponseBody
        type: object
        properties:
            message:
                type: string
                description: User message
                example: Quibusdam quod voluptates est vitae quo quo.
        example:
            message: Est suscipit aliquid nam.
        required:
            - message
