openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for interceptors
paths:
    /records/{tenantID}:
        post:
            tags:
                - interceptors
            summary: create interceptors
            description: Create a new record with all interceptors in action
            operationId: interceptors#create
            parameters:
                - name: tenantID
                  in: path
                  description: Tenant ID for the request
                  required: true
                  schema:
                    type: string
                    description: Tenant ID for the request
                    example: 66c20bbb-15ff-4254-b34a-4ecbeff0ce29
                    format: uuid
                  example: 66c20bbb-15ff-4254-b34a-4ecbeff0ce29
                - name: Authorization
                  in: header
                  description: JWT auth token
                  required: true
                  schema:
                    type: string
                    description: JWT auth token
                    example: Voluptatum necessitatibus.
                  example: Consequatur excepturi quam quia laudantium asperiores.
            requestBody:
                description: Request body for create.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/CreateRequestBody'
                        example:
                            spanID: 7e046fe3-fa36-4f0f-b281-f8c9e1fdf010
                            traceID: 831384a5-5a7d-43cc-94e4-5ec22455f386
                            value: Impedit voluptatem culpa et.
            responses:
                "201":
                    description: Created response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/CreateResponseBody'
                            example:
                                duration: 2675830902084894015
                                id: 612f2f00-a808-44b9-a52d-a7f34bf838a4
                                processedAt: Id quaerat dolores ab quo soluta modi.
                                retryCount: 193182529652580268
                                retryDuration: 5809970416232694733
                                status: 2668736938289029744
                                tenant: Sed omnis aut recusandae fuga minima.
                                value: Fuga quia.
    /records/{tenantID}/{recordID}:
        get:
            tags:
                - interceptors
            summary: get interceptors
            description: Get retrieves a record by ID with all interceptors in action
            operationId: interceptors#get
            parameters:
                - name: tenantID
                  in: path
                  description: Tenant ID for the request
                  required: true
                  schema:
                    type: string
                    description: Tenant ID for the request
                    example: 66c20bbb-15ff-4254-b34a-4ecbeff0ce29
                    format: uuid
                  example: 66c20bbb-15ff-4254-b34a-4ecbeff0ce29
                - name: recordID
                  in: path
                  description: ID of the record to retrieve
                  required: true
                  schema:
                    type: string
                    description: ID of the record to retrieve
                    example: 66c20bbb-15ff-4254-b34a-4ecbeff0ce29
                    format: uuid
                  example: 66c20bbb-15ff-4254-b34a-4ecbeff0ce29
                - name: Authorization
                  in: header
                  description: JWT auth token
                  required: true
                  schema:
                    type: string
                    description: JWT auth token
                    example: Beatae eum.
                  example: Voluptate perferendis dicta commodi.
            requestBody:
                description: Request body for get.
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/GetRequestBody'
                        example:
                            spanID: c2bc78f1-a675-44df-b132-1d285e204cf2
                            traceID: 8909bcf0-fa7e-4ed1-bc3e-1ed689cc9896
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetResponseBody'
                            example:
                                cachedAt: Aut vero voluptates.
                                duration: 966071656546526256
                                id: f9922b04-e873-4efc-9b16-fdcb9d29ef0a
                                processedAt: Asperiores voluptatem quisquam id necessitatibus.
                                retryCount: 1538090001739738220
                                retryDuration: 3066832311296962951
                                status: 6370274974021655670
                                tenant: Ad consequatur dolor alias.
                                value: Impedit officiis.
                "404":
                    description: 'NotFound: Record not found'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "503":
                    description: 'Unavailable: Temporary error'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /records/{tenantID}/stream:
        get:
            tags:
                - interceptors
            summary: stream interceptors
            description: Stream records
            operationId: interceptors#stream
            parameters:
                - name: tenantID
                  in: path
                  description: Tenant ID for the request
                  required: true
                  schema:
                    type: string
                    description: Tenant ID for the request
                    example: 66c20bbb-15ff-4254-b34a-4ecbeff0ce29
                    format: uuid
                  example: 66c20bbb-15ff-4254-b34a-4ecbeff0ce29
                - name: Authorization
                  in: header
                  description: JWT auth token
                  required: true
                  schema:
                    type: string
                    description: JWT auth token
                    example: Aliquid et dignissimos delectus facere nesciunt.
                  example: Aut expedita eum id.
            responses:
                "101":
                    description: Switching Protocols response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/StreamResponseBody'
                            example:
                                id: 1bbd1751-b7df-4308-a1c7-0a55a307585d
                                spanID: baffd1d3-7d92-456b-a4f1-37f462d4c356
                                status: 3407397389909827570
                                tenant: Repellendus eveniet sit.
                                traceID: 871ffc91-4efb-4fdb-a84b-8561f8f11b47
                                value: Eos nihil.
components:
    schemas:
        CreateRequestBody:
            type: object
            properties:
                spanID:
                    type: string
                    description: Unique span ID for request, initialized by the TraceRequest interceptor
                    example: c89c4a4e-7182-4507-864e-8c8476e91061
                    format: uuid
                traceID:
                    type: string
                    description: Unique trace ID for request, initialized by the TraceRequest interceptor
                    example: c89c4a4e-7182-4507-864e-8c8476e91061
                    format: uuid
                value:
                    type: string
                    description: Value to store in record
                    example: Impedit voluptatem culpa et.
            description: Request body for create.
            example:
                spanID: c89c4a4e-7182-4507-864e-8c8476e91061
                traceID: c89c4a4e-7182-4507-864e-8c8476e91061
                value: Impedit voluptatem culpa et.
            required:
                - value
        CreateResponseBody:
            type: object
            properties:
                duration:
                    type: integer
                    description: Processing duration in ms
                    example: 2675830902084894015
                    format: int64
                id:
                    type: string
                    description: ID of the created record
                    example: 7673f207-d6bd-473a-8f84-1c0b64fcfc54
                    format: uuid
                processedAt:
                    type: string
                    description: Timestamp when processed
                    example: Id quaerat dolores ab quo soluta modi.
                retryCount:
                    type: integer
                    description: Number of retry attempts made
                    example: 193182529652580268
                    format: int64
                retryDuration:
                    type: integer
                    description: Total time spent retrying
                    example: 5809970416232694733
                    format: int64
                status:
                    type: integer
                    description: Response status code
                    example: 2668736938289029744
                    format: int64
                tenant:
                    type: string
                    description: Tenant the record belongs to
                    example: Sed omnis aut recusandae fuga minima.
                value:
                    type: string
                    description: Value of the record
                    example: Fuga quia.
            example:
                duration: 2675830902084894015
                id: 7673f207-d6bd-473a-8f84-1c0b64fcfc54
                processedAt: Id quaerat dolores ab quo soluta modi.
                retryCount: 193182529652580268
                retryDuration: 5809970416232694733
                status: 2668736938289029744
                tenant: Sed omnis aut recusandae fuga minima.
                value: Fuga quia.
            required:
                - id
                - value
                - tenant
                - status
                - processedAt
                - duration
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            description: Record not found
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: true
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        GetRequestBody:
            type: object
            properties:
                spanID:
                    type: string
                    description: Unique span ID for request, initialized by the TraceRequest interceptor
                    example: c89c4a4e-7182-4507-864e-8c8476e91061
                    format: uuid
                traceID:
                    type: string
                    description: Unique trace ID for request, initialized by the TraceRequest interceptor
                    example: c89c4a4e-7182-4507-864e-8c8476e91061
                    format: uuid
            description: Request body for get.
            example:
                spanID: c89c4a4e-7182-4507-864e-8c8476e91061
                traceID: c89c4a4e-7182-4507-864e-8c8476e91061
        GetResponseBody:
            type: object
            properties:
                cachedAt:
                    type: string
                    description: Time at which the record was cached, written by the Cache interceptor
                    example: Aut vero voluptates.
                duration:
                    type: integer
                    description: Processing duration in ms, written by the RequestAudit interceptor
                    example: 966071656546526256
                    format: int64
                id:
                    type: string
                    description: ID of the record
                    example: 7673f207-d6bd-473a-8f84-1c0b64fcfc54
                    format: uuid
                processedAt:
                    type: string
                    description: Timestamp when processed, written by the RequestAudit interceptor
                    example: Asperiores voluptatem quisquam id necessitatibus.
                retryCount:
                    type: integer
                    description: Number of retry attempts made, written client-side by the Retry interceptor
                    example: 1538090001739738220
                    format: int64
                retryDuration:
                    type: integer
                    description: Total time spent retrying, written client-side by the Retry interceptor
                    example: 3066832311296962951
                    format: int64
                status:
                    type: integer
                    description: Response status code
                    example: 6370274974021655670
                    format: int64
                tenant:
                    type: string
                    description: Tenant the record belongs to
                    example: Ad consequatur dolor alias.
                value:
                    type: string
                    description: Value of the record
                    example: Impedit officiis.
            example:
                cachedAt: Aut vero voluptates.
                duration: 966071656546526256
                id: 7673f207-d6bd-473a-8f84-1c0b64fcfc54
                processedAt: Asperiores voluptatem quisquam id necessitatibus.
                retryCount: 1538090001739738220
                retryDuration: 3066832311296962951
                status: 6370274974021655670
                tenant: Ad consequatur dolor alias.
                value: Impedit officiis.
            required:
                - id
                - value
                - tenant
                - status
                - processedAt
                - duration
        StreamResponseBody:
            type: object
            properties:
                id:
                    type: string
                    description: ID of the created record
                    example: 7673f207-d6bd-473a-8f84-1c0b64fcfc54
                    format: uuid
                spanID:
                    type: string
                    description: Unique span ID for request, initialized by the TraceRequest interceptor
                    example: 7673f207-d6bd-473a-8f84-1c0b64fcfc54
                    format: uuid
                status:
                    type: integer
                    description: Response status code
                    example: 3407397389909827570
                    format: int64
                tenant:
                    type: string
                    description: Tenant the record belongs to
                    example: Repellendus eveniet sit.
                traceID:
                    type: string
                    description: Unique trace ID for request, initialized by the TraceRequest interceptor
                    example: 7673f207-d6bd-473a-8f84-1c0b64fcfc54
                    format: uuid
                value:
                    type: string
                    description: Value of the record
                    example: Eos nihil.
            example:
                id: 7673f207-d6bd-473a-8f84-1c0b64fcfc54
                spanID: 7673f207-d6bd-473a-8f84-1c0b64fcfc54
                status: 3407397389909827570
                tenant: Repellendus eveniet sit.
                traceID: 7673f207-d6bd-473a-8f84-1c0b64fcfc54
                value: Eos nihil.
            required:
                - id
                - value
                - tenant
                - status
        StreamStreamingBody:
            type: object
            properties:
                id:
                    type: string
                    description: ID of the created record
                    example: 4ebe4239-1377-48a0-a82d-aeb7fb4a79aa
                    format: uuid
                spanID:
                    type: string
                    description: Unique span ID for request, initialized by the TraceRequest interceptor
                    example: 4ebe4239-1377-48a0-a82d-aeb7fb4a79aa
                    format: uuid
                traceID:
                    type: string
                    description: Unique trace ID for request, initialized by the TraceRequest interceptor
                    example: 4ebe4239-1377-48a0-a82d-aeb7fb4a79aa
                    format: uuid
                value:
                    type: string
                    description: Value of the record
                    example: Enim qui sint.
            example:
                id: 4ebe4239-1377-48a0-a82d-aeb7fb4a79aa
                spanID: 4ebe4239-1377-48a0-a82d-aeb7fb4a79aa
                traceID: 4ebe4239-1377-48a0-a82d-aeb7fb4a79aa
                value: Enim qui sint.
            required:
                - id
                - value
tags:
    - name: interceptors
      description: |-
        The interceptors service demonstrates a comprehensive use of interceptors combining
        authentication, tenant validation, caching, audit logging, and retry mechanisms. It showcases
        both client-side and server-side interceptors working together to provide a robust service.
