#! /usr/bin/make
#
# These commands use the calculator example's generated packages. They have no
# local design to regenerate, but must build and test during a repository release.

.PHONY: all test

all: test

test:
	go test ./...
