openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for concat
paths:
    /concat/{a}/{b}:
        get:
            tags:
                - concat
            summary: concat concat
            operationId: concat#concat
            parameters:
                - name: a
                  in: path
                  description: Left operand
                  required: true
                  schema:
                    type: string
                    description: Left operand
                    example: Non molestiae ipsam et possimus nesciunt.
                  example: Non molestiae ipsam et possimus nesciunt.
                - name: b
                  in: path
                  description: Right operand
                  required: true
                  schema:
                    type: string
                    description: Right operand
                    example: Commodi inventore quos.
                  example: Commodi inventore quos.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                type: string
                                example: Atque modi odio fugiat dolor quis laboriosam.
                            example: Atque modi odio fugiat dolor quis laboriosam.
components: {}
tags:
    - name: concat
      description: |
        The concat service performs operations on strings.

        The service uses the CBOR binary serialization standard to encode responses.
        It supports reading requests encoded with CBOR, JSON, XML or GOB.
