swagger: "2.0"
info:
    title: ""
    version: 0.0.1
host: localhost:80
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /{filepath}:
        get:
            tags:
                - events
            summary: Download public
            operationId: events#/{*filepath}
            parameters:
                - name: filepath
                  in: path
                  description: Relative file path
                  required: true
                  type: string
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
                "404":
                    description: File not found
                    schema:
                        $ref: '#/definitions/Error'
            schemes:
                - http
    /events/stream:
        get:
            tags:
                - events
            summary: stream events
            description: Stream events using Server-Sent Events
            operationId: events#stream
            produces:
                - text/event-stream
            responses:
                "200":
                    description: OK response.
            schemes:
                - http
    /events/trigger:
        post:
            tags:
                - events
            summary: trigger events
            description: Trigger a new event to be sent to all connected clients
            operationId: events#trigger
            parameters:
                - name: TriggerRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/EventsTriggerRequestBody'
                    required:
                        - message
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/EventsTriggerResponseBody'
                        required:
                            - status
            schemes:
                - http
definitions:
    Error:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Error response result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    EventsTriggerRequestBody:
        title: EventsTriggerRequestBody
        type: object
        properties:
            message:
                type: string
                description: Message to broadcast
                example: Something happened!
        example:
            message: Something happened!
        required:
            - message
    EventsTriggerResponseBody:
        title: EventsTriggerResponseBody
        type: object
        properties:
            status:
                type: string
                description: Status of the operation
                example: Non aliquid facilis vel vitae qui.
        example:
            status: Sint laboriosam nisi et.
        required:
            - status
