openapi: 3.0.3
info:
    title: Goa API
    version: 0.0.1
servers:
    - url: http://localhost:80
      description: Default server for events
paths:
    /{*filepath}:
        get:
            tags:
                - events
            summary: Download public
            operationId: events#/{*filepath}
            parameters:
                - name: filepath
                  in: path
                  description: Relative file path
                  required: true
            responses:
                "200":
                    description: File not found
                "404":
                    description: File not found
    /events/stream:
        get:
            tags:
                - events
            summary: stream events
            description: Stream events using Server-Sent Events
            operationId: events#stream
            responses:
                "200":
                    description: OK response.
                    content:
                        text/event-stream:
                            schema:
                                type: string
                                format: binary
    /events/trigger:
        post:
            tags:
                - events
            summary: trigger events
            description: Trigger a new event to be sent to all connected clients
            operationId: events#trigger
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/TriggerRequestBody'
                        example:
                            message: Something happened!
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/TriggerResponseBody'
                            example:
                                status: Dolorem soluta facilis.
components:
    schemas:
        TriggerRequestBody:
            type: object
            properties:
                message:
                    type: string
                    description: Message to broadcast
                    example: Something happened!
            example:
                message: Something happened!
            required:
                - message
        TriggerResponseBody:
            type: object
            properties:
                status:
                    type: string
                    description: Status of the operation
                    example: Quasi dolor assumenda repudiandae nihil.
            example:
                status: Temporibus inventore est.
            required:
                - status
tags:
    - name: events
      description: The events service provides real-time updates via SSE
